name: Docker Image CI

on:
  push:
    tags:
      - n8n@*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:14})
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.NCLOUD_IMAGE_URL }}
        username: ${{ secrets.NCLOUD_USERNAME }}
        password: ${{ secrets.NCLOUD_PASSWORD }}
    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: |
          N8N_VERSION=${{steps.vars.outputs.tag}}
        push: true
        tags: |
          ${{ secrets.NCLOUD_IMAGE_URL }}/n8n:${{ steps.vars.outputs.tag }}
          ${{ secrets.NCLOUD_IMAGE_URL }}/n8n:latest
